package expo.modules.noutubeview

import android.app.Activity
import android.content.*
import android.content.pm.ActivityInfo
import android.graphics.Bitmap
import android.net.Uri
import android.os.IBinder
import android.os.PowerManager
import android.provider.Settings
import android.util.AttributeSet
import android.view.*
import android.webkit.*
import android.widget.FrameLayout
import androidx.core.view.*
import expo.modules.kotlin.AppContext
import expo.modules.kotlin.viewevent.EventDispatcher
import expo.modules.kotlin.views.ExpoView
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume

val VIEW_HOSTS=arrayOf("youtube.com","youtu.be")
val KORNDOG_THEME_CSS=""":root{--yt-spec-base-background:#120020!important;--yt-spec-raised-background:#1a0a2e!important;--yt-spec-menu-background:#2d1450!important;--yt-spec-brand-background-solid:#2d1450!important;--yt-spec-general-background-a:#120020!important;--yt-spec-general-background-b:#1a0a2e!important;--yt-spec-general-background-c:#2d1450!important;--yt-spec-call-to-action:#39ff14!important;--yt-spec-static-brand-red:#39ff14!important;--yt-spec-text-primary:#f0eaf8!important;--yt-spec-text-secondary:#bba7d9!important;--yt-spec-icon-active-other:#39ff14!important;--yt-spec-brand-icon-active:#39ff14!important}ytmusic-nav-bar,#nav-bar-background,ytmusic-player-bar{background:#2d1450!important}ytmusic-player-bar{border-top:3px solid #39ff14!important;box-shadow:0 -2px 18px rgba(57,255,20,.18)!important}ytmusic-player-bar .title,.content-info-wrapper .title,ytmusic-player-page .title{color:#39ff14!important}ytmusic-player-bar .subtitle,.content-info-wrapper .subtitle,ytmusic-player-page .subtitle{color:#bba7d9!important}tp-yt-paper-slider #progressContainer #primaryProgress{background:#39ff14!important}ytmusic-chip-cloud-chip-renderer,ytmusic-responsive-list-item-renderer:hover,tp-yt-paper-listbox,ytmusic-menu-popup-renderer{background:#2d1450!important}ytmusic-player-page,ytmusic-browse-response,ytmusic-section-list-renderer{background:#120020!important;color:#f0eaf8!important}""".replace("'","\\'")

val KORNDOG_QUEUE_TRACKER_SCRIPT="""
(function(){if(window._kdQueueTrackerInit)return;window._kdQueueTrackerInit=true;
var KEY='korndog_queue',MAX=5,last='',lastProg=0;
function clean(t){return(t||'').replace(/\s+/g,' ').replace(/Explicit|Album|Song|Video/g,'').trim()}
function up(u){if(!u)return'';return u.replace(/=w[0-9]+-h[0-9]+.*$/i,'=w800-h800-l90-rj').replace(/\/s[0-9]+\//i,'/s800/')}
function q(){try{var s=localStorage.getItem(KEY);return s?JSON.parse(s):[]}catch(e){return[]}}
function save(a){try{localStorage.setItem(KEY,JSON.stringify(a))}catch(e){}}
function thumb(){var spots=['ytmusic-player-bar img','ytmusic-player img','.player-bar img','.miniplayer img'];for(var x=0;x<spots.length;x++){var im=document.querySelector(spots[x]);if(im){var src=im.currentSrc||im.src||'';if(src&&(src.indexOf('ytimg')>-1||src.indexOf('googleusercontent')>-1))return up(src)}}var title=(document.querySelector('ytmusic-player-bar .title')||document.querySelector('.content-info-wrapper .title')||{}).innerText||'';var rows=Array.from(document.querySelectorAll('ytmusic-responsive-list-item-renderer,tp-yt-paper-item,ytmusic-player-queue-item'));for(var r=0;r<rows.length;r++){var txt=(rows[r].innerText||'');if(title&&txt.indexOf(title)>-1){var img=rows[r].querySelector('img');if(img){var s=img.currentSrc||img.src||'';if(s)return up(s)}}}var imgs=Array.from(document.querySelectorAll('ytmusic-player-bar img,img')).filter(function(i){var s=i.currentSrc||i.src||'';if(!s)return false;if(s.indexOf('ytimg')<0&&s.indexOf('googleusercontent')<0)return false;var r=i.getBoundingClientRect();return r.width>=24&&r.height>=24&&r.width<500&&r.height<500}).sort(function(a,b){var ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return Math.abs((ar.width*ar.height)-4096)-Math.abs((br.width*br.height)-4096)});if(imgs.length)return up(imgs[0].currentSrc||imgs[0].src);var og=document.querySelector('meta[property="og:image"],meta[name="twitter:image"]');if(og&&og.content)return up(og.content);var a=q();return a.length&&a[0].thumb?a[0].thumb:''}
function info(){var title='',artist='',seconds=0,m=document.querySelector('video,audio');if(m)seconds=Math.floor(m.duration||0);var te=document.querySelector('ytmusic-player-bar .title')||document.querySelector('.content-info-wrapper .title')||document.querySelector('ytmusic-player-page .title');if(te)title=clean(te.innerText||te.textContent);var ae=document.querySelector('ytmusic-player-bar .subtitle')||document.querySelector('.content-info-wrapper .subtitle')||document.querySelector('ytmusic-player-page .subtitle');if(ae)artist=clean(ae.innerText||ae.textContent);if(artist.indexOf(' • ')>-1)artist=artist.split(' • ')[0].trim();if(artist.indexOf(' - ')>-1)artist=artist.split(' - ')[0].trim();var ot=document.querySelector('meta[property="og:title"]');if(!title&&ot&&ot.content)title=clean(ot.content);var od=document.querySelector('meta[property="og:description"]');if(!artist&&od&&od.content)artist=clean(od.content);return{title:title,artist:artist,thumb:thumb(),seconds:seconds}}
function send(i){try{if(!i.title||!i.artist)return;if(!i.thumb){var a=q();if(a.length&&a[0].thumb)i.thumb=a[0].thumb}if(window.NouTubeI&&window.NouTubeI.notify)window.NouTubeI.notify(i.title,i.artist,String(i.seconds||0),i.thumb||'')}catch(e){}}
function prog(){try{var m=document.querySelector('video,audio');if(!m)return;var n=Date.now();if(n-lastProg<1000)return;lastProg=n;if(window.NouTubeI&&window.NouTubeI.notifyProgress)window.NouTubeI.notifyProgress(String(!m.paused),String(Math.floor(m.currentTime||0)))}catch(e){}}
function add(i){if(!i.title||!i.artist)return;var a=q();if(a.length&&a[0].title===i.title&&a[0].artist===i.artist){if(i.thumb){a[0].thumb=i.thumb;save(a)}else if(a[0].thumb)i.thumb=a[0].thumb;send(i);return}a.unshift({title:i.title,artist:i.artist,thumb:i.thumb||'',played:Date.now()});if(a.length>MAX)a=a.slice(0,MAX);save(a);send(i)}
function tick(){try{var i=info(),k=i.title+'|'+i.artist;if(k&&i.title&&i.artist){if(k!==last){last=k;add(i)}else add(i)}prog()}catch(e){}}
setInterval(tick,1500);document.addEventListener('play',function(){setTimeout(tick,250)},true);document.addEventListener('pause',function(){setTimeout(tick,250)},true);document.addEventListener('timeupdate',tick,true);setTimeout(tick,500);setTimeout(tick,2000);setTimeout(tick,5000);
})();
""".trimIndent()

val KORNDOG_CAST_SCRIPT="""
(function(){function theme(){try{var s=document.getElementById('korndog-theme');if(s)s.remove();var st=document.createElement('style');st.id='korndog-theme';st.textContent='${KORNDOG_THEME_CSS}';document.head.appendChild(st)}catch(e){}}theme();setInterval(theme,2500);
function tv(){if(!document.body){setTimeout(tv,500);return}if(document.getElementById('korndog-tv-btn'))return;var b=document.createElement('button');b.id='korndog-tv-btn';b.textContent='📺';b.setAttribute('aria-label','Open KornDog Generator');b.style.cssText='position:fixed;right:14px;bottom:116px;z-index:999999;width:38px;height:38px;border-radius:13px;border:1px solid rgba(57,255,20,.55);background:rgba(45,20,80,.82);color:#39ff14;font-size:20px;display:flex;align-items:center;justify-content:center;box-shadow:0 0 16px rgba(57,255,20,.35);backdrop-filter:blur(10px);padding:0;margin:0;cursor:pointer;touch-action:manipulation;';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openGen();return false});document.body.appendChild(b)}
function openGen(){try{var q=[];try{q=JSON.parse(localStorage.getItem('korndog_queue')||'[]')}catch(e){}var song=q&&q.length?q[0]:null,p=new URLSearchParams();p.set('from','ghostkernel');if(song){if(song.artist)p.set('artist',song.artist);if(song.title)p.set('album',song.title);if(song.thumb)p.set('thumb',song.thumb)}window.location.href='https://korndogrecords.com/korndog-spinning-generator.html?'+p.toString()}catch(e){window.location.href='https://korndogrecords.com/korndog-spinning-generator.html?from=ghostkernel'}}
setTimeout(tv,1000);
if(!window._kdAudioNormInit){window._kdAudioNormInit=true;var A=window.AudioContext||window.webkitAudioContext;if(A){var c=new A();window._kdAudioCtx=c;var comp=c.createDynamicsCompressor();comp.threshold.value=-35;comp.knee.value=20;comp.ratio.value=8;comp.attack.value=.005;comp.release.value=.2;var g=c.createGain();g.gain.value=2;comp.connect(g);g.connect(c.destination);function hook(el){try{if(!el._kdHooked){el._kdHooked=true;var src=c.createMediaElementSource(el);src.connect(comp);if(c.state==='suspended')c.resume()}}catch(e){}}function all(){document.querySelectorAll('audio,video').forEach(hook)}var o=new MutationObserver(all);o.observe(document.documentElement,{childList:true,subtree:true});all();setTimeout(all,2000);setTimeout(all,5000)}}
if(!window._kdAudioResumeInit){window._kdAudioResumeInit=true;document.addEventListener('touchstart',function(){try{if(window._kdAudioCtx&&window._kdAudioCtx.state==='suspended')window._kdAudioCtx.resume()}catch(e){}},{passive:true})}
if(!window._kdSmartKeepAliveInit){window._kdSmartKeepAliveInit=true;window._kdUserPaused=false;window._kdShouldBePlaying=false;window._kdLastMediaTime=0;window._kdLastMediaCheck=Date.now();window._kdRecovering=false;window._kdLastForcedPlay=0;function m(){return document.querySelector('video,audio')}function play(x){try{if(!x||window._kdUserPaused)return;var n=Date.now();if(n-window._kdLastForcedPlay<1200)return;window._kdLastForcedPlay=n;var p=x.play();if(p&&p.catch)p.catch(function(){})}catch(e){}}function markPlay(){window._kdUserPaused=false;window._kdShouldBePlaying=true}function markPause(){var x=m();if(!x)return;if(window._kdRecovering)return;if(x.readyState<3||x.networkState===2)return;if(x.currentTime>0&&!x.ended){window._kdUserPaused=true;window._kdShouldBePlaying=false}}
document.addEventListener('play',function(e){if(e.target&&(e.target.tagName==='VIDEO'||e.target.tagName==='AUDIO'))markPlay()},true);document.addEventListener('pause',function(e){if(e.target&&(e.target.tagName==='VIDEO'||e.target.tagName==='AUDIO'))markPause()},true);['waiting','stalled','suspend','emptied','error','abort'].forEach(function(ev){document.addEventListener(ev,function(e){if(e.target&&(e.target.tagName==='VIDEO'||e.target.tagName==='AUDIO')){if(!window._kdUserPaused)window._kdShouldBePlaying=true}},true)});document.addEventListener('visibilitychange',function(){var x=m();if(x&&window._kdShouldBePlaying&&!window._kdUserPaused)play(x)},true);
setInterval(function(){try{var x=m();if(!x)return;var n=Date.now(),cur=x.currentTime||0,paused=x.paused,ended=x.ended,ready=x.readyState||0,net=x.networkState||0;if(!paused&&!ended){window._kdShouldBePlaying=true;window._kdUserPaused=false}var moved=Math.abs(cur-window._kdLastMediaTime)>.12,stuck=window._kdShouldBePlaying&&!window._kdUserPaused&&!ended&&!moved&&n-window._kdLastMediaCheck>2200,buf=window._kdShouldBePlaying&&!window._kdUserPaused&&!ended&&ready<3,fake=window._kdShouldBePlaying&&!window._kdUserPaused&&!ended&&(net===2||net===3||ready===0);if((stuck||buf||fake||paused)&&window._kdShouldBePlaying&&!window._kdUserPaused){window._kdRecovering=true;try{if(net===3||ready===0)x.load()}catch(e){}play(x);setTimeout(function(){window._kdRecovering=false},900)}window._kdLastMediaTime=cur;window._kdLastMediaCheck=n}catch(e){}},900)}
})();
""".trimIndent()

val KORNDOG_SYNCED_LYRICS_SCRIPT="""
(function(){if(window._kdLyricsHighlightInit)return;window._kdLyricsHighlightInit=true;function css(){var o=document.getElementById('korndog-lyrics-highlight-style');if(o)o.remove();var s=document.createElement('style');s.id='korndog-lyrics-highlight-style';s.textContent=`ytmusic-description-shelf-renderer,ytmusic-description-shelf-renderer *,ytmusic-player-section-list-renderer,ytmusic-player-section-list-renderer *,ytmusic-player-page [role="tabpanel"],ytmusic-player-page [role="tabpanel"] *,.lyrics,.lyrics *,.lyrics-wrapper,.lyrics-wrapper *{color:#d8ffd0!important}.korndog-lyric-line{display:inline-block!important;color:#d8ffd0!important;transition:color .2s ease,text-shadow .2s ease,transform .2s ease!important}.korndog-lyric-active{color:#39ff14!important;font-weight:900!important;text-shadow:0 0 12px rgba(57,255,20,.95),0 0 24px rgba(57,255,20,.55)!important;transform:scale(1.025)!important}`;document.head.appendChild(s)}
css();setInterval(css,3000);function vis(e){if(!e)return false;var r=e.getBoundingClientRect();return r.width>0&&r.height>0}function box(){var ss=['ytmusic-description-shelf-renderer','ytmusic-player-section-list-renderer','ytmusic-player-page [role="tabpanel"]','.lyrics-wrapper','.lyrics'];for(var i=0;i<ss.length;i++){var ns=document.querySelectorAll(ss[i]);for(var j=0;j<ns.length;j++){var e=ns[j],t=(e.innerText||'').trim();if(vis(e)&&t.length>60)return e}}return null}function wrap(c){if(!c||c._kdLyricsWrapped)return;c._kdLyricsWrapped=true;var w=document.createTreeWalker(c,NodeFilter.SHOW_TEXT,null),nodes=[],n;while((n=w.nextNode())){var t=(n.textContent||'').trim();if(t.indexOf('Source:')===0||t.indexOf('Musixmatch')>-1||t.indexOf('LyricFind')>-1)return;if(t.length>2&&t.length<220&&n.parentElement&&vis(n.parentElement))nodes.push(n)}nodes.forEach(function(n,i){try{if(n.parentElement&&n.parentElement.classList.contains('korndog-lyric-line'))return;var s=document.createElement('span');s.className='korndog-lyric-line';s.setAttribute('data-korndog-lyric-index',String(i));n.parentNode.insertBefore(s,n);s.appendChild(n)}catch(e){}})}function hi(){var lines=Array.from(document.querySelectorAll('.korndog-lyric-line'));if(!lines.length)return;var y=window.innerHeight*.42,b=null,d=Infinity;lines.forEach(function(l){if(!vis(l))return;var r=l.getBoundingClientRect(),x=Math.abs(r.top-y);if(x<d){d=x;b=l}});lines.forEach(function(l){l.classList.remove('korndog-lyric-active')});if(b)b.classList.add('korndog-lyric-active')}setInterval(function(){try{var c=box();if(c){wrap(c);hi()}}catch(e){}},500);
})();
""".trimIndent()

class NouWebView @JvmOverloads constructor(c:Context,a:AttributeSet?=null,d:Int=0):WebView(c,a,d){
  override fun onWindowVisibilityChanged(v:Int){super.onWindowVisibilityChanged(VISIBLE)}
  init{settings.run{javaScriptEnabled=true;domStorageEnabled=true;mediaPlaybackRequiresUserGesture=false;supportZoom();builtInZoomControls=true;displayZoomControls=false;cacheMode=WebSettings.LOAD_DEFAULT;loadsImagesAutomatically=true;blockNetworkImage=false;blockNetworkLoads=false;allowFileAccess=true;allowContentAccess=true};CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(this,true);setFocusable(true);setFocusableInTouchMode(true)}
  suspend fun eval(s:String):String?=suspendCancellableCoroutine{c->evaluateJavascript(s){r->c.resume(if(r=="null")null else r.removeSurrounding("\""))}}
}
class NouOrientationListener(c:Context,private val v:NouTubeView):OrientationEventListener(c){override fun onOrientationChanged(o:Int){v.onOrientationChanged(o)}}
class NouTubeView(context:Context,appContext:AppContext):ExpoView(context,appContext){
  private val onLoad by EventDispatcher();internal val onMessage by EventDispatcher();private var scriptOnStart="";private var pageUrl="";private var customView:View?=null;private lateinit var orientationListener:NouOrientationListener;internal val nouCast=NouCast(context)
  private val gestureDetector=GestureDetector(context,object:GestureDetector.SimpleOnGestureListener(){override fun onScroll(e1:MotionEvent?,e2:MotionEvent,dx:Float,dy0:Float):Boolean{var dy=dy0;if(e1!=null)dy=(e2.y-e1.y)/context.resources.displayMetrics.density;emit("scroll",mapOf("dy" to dy,"y" to webView.scrollY));return false}})
  private var service:NouService?=null;private var powerManager:PowerManager?=null;private var wakeLock:PowerManager.WakeLock?=null;internal val currentActivity:Activity? get()=appContext.activityProvider?.currentActivity
  override fun onCreateContextMenu(menu:ContextMenu){super.onCreateContextMenu(menu);val r=webView.hitTestResult;val a=currentActivity;var u:String?=null;if(r.type==WebView.HitTestResult.SRC_ANCHOR_TYPE)u=r.extra else if(r.type==WebView.HitTestResult.SRC_IMAGE_ANCHOR_TYPE){val h=webView.handler.obtainMessage();webView.requestFocusNodeHref(h);u=h.data?.getString("url")};if(u!=null&&a!=null)menu.add("Copy link").setOnMenuItemClickListener{val cm=a.getSystemService(Context.CLIPBOARD_SERVICE)as ClipboardManager;cm.setPrimaryClip(ClipData.newPlainText("link",u));true}}
  internal val webView:NouWebView=NouWebView(context).apply{
    layoutParams=LayoutParams(LayoutParams.MATCH_PARENT,LayoutParams.MATCH_PARENT);setOnTouchListener{_,e->gestureDetector.onTouchEvent(e);false}
    webViewClient=object:WebViewClient(){override fun doUpdateVisitedHistory(v:WebView,u:String,isReload:Boolean){if(pageUrl!=u){pageUrl=u;onLoad(mapOf("url" to pageUrl))}};override fun onPageStarted(v:WebView,u:String,f:Bitmap?){evaluateJavascript(scriptOnStart,null)};override fun onPageFinished(v:WebView,u:String){evaluateJavascript(KORNDOG_CAST_SCRIPT,null);evaluateJavascript(KORNDOG_QUEUE_TRACKER_SCRIPT,null);evaluateJavascript(KORNDOG_SYNCED_LYRICS_SCRIPT,null)};override fun shouldInterceptRequest(v:WebView,r:WebResourceRequest):WebResourceResponse?=null;override fun shouldOverrideUrlLoading(v:WebView,u:String):Boolean{val uri=Uri.parse(u);return if(uri.host in VIEW_HOSTS||uri.host?.startsWith("accounts.google.")==true||uri.host?.startsWith("gds.google.")==true||uri.host?.endsWith(".youtube.com")==true)false else{v.context.startActivity(Intent(Intent.ACTION_VIEW,uri));true}}}
    webChromeClient=object:WebChromeClient(){override fun onPermissionRequest(r:PermissionRequest){val a=currentActivity;if(a==null){r.deny();return};val ps=mutableListOf<String>();if(r.resources.contains(PermissionRequest.RESOURCE_AUDIO_CAPTURE))ps.add(android.Manifest.permission.RECORD_AUDIO);if(r.resources.contains(PermissionRequest.RESOURCE_VIDEO_CAPTURE))ps.add(android.Manifest.permission.CAMERA);if(ps.isEmpty()){r.grant(r.resources);return};a.requestPermissions(ps.toTypedArray(),101);r.grant(r.resources)};override fun onJsBeforeUnload(v:WebView,u:String,m:String,res:JsResult):Boolean{res.confirm();return true};override fun onShowCustomView(v:View,cb:CustomViewCallback){customView=v;v.keepScreenOn=true;val a=currentActivity?:return;val w=a.window;(w.decorView as FrameLayout).addView(v,FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));a.requestedOrientation=ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;val c=WindowCompat.getInsetsController(w,w.decorView);c.hide(WindowInsetsCompat.Type.systemBars());c.systemBarsBehavior=WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE;if(Settings.System.getInt(a.contentResolver,Settings.System.ACCELEROMETER_ROTATION,0)==1)orientationListener.enable()};override fun onHideCustomView(){val a=currentActivity?:return;val w=a.window;(w.decorView as FrameLayout).removeView(customView);customView?.keepScreenOn=false;customView=null;a.requestedOrientation=ActivityInfo.SCREEN_ORIENTATION_USER;val c=WindowCompat.getInsetsController(w,w.decorView);c.show(WindowInsetsCompat.Type.systemBars());c.systemBarsBehavior=WindowInsetsControllerCompat.BEHAVIOR_DEFAULT;this@apply.requestFocus();orientationListener.disable()}}
  }
  init{addView(webView);initService();initWakeLock();currentActivity?.registerForContextMenu(webView);webView.addJavascriptInterface(NouJsInterface(context,this),"NouTubeI");ViewCompat.setOnApplyWindowInsetsListener(webView){_,_->WindowInsetsCompat.CONSUMED}}
  private fun initWakeLock(){powerManager=context.getSystemService(Context.POWER_SERVICE)as PowerManager?;wakeLock=powerManager?.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"NouTube::PlaybackWakeLock")}
  fun initService(){val a=currentActivity?:return;val conn=object:ServiceConnection{override fun onServiceConnected(n:ComponentName,b:IBinder){val nb=b as NouService.NouBinder;service=nb.getService();service?.initialize(webView,a);nouController.service=service;nouController.applyPendingSleepTimer()};override fun onServiceDisconnected(n:ComponentName){}};val i=Intent(a,NouService::class.java);androidx.core.content.ContextCompat.startForegroundService(a,i);a.bindService(i,conn,Context.BIND_AUTO_CREATE);orientationListener=NouOrientationListener(a,this)}
  fun setScriptOnStart(s:String){scriptOnStart=s}
  fun clearData(){val cm=CookieManager.getInstance();if(android.os.Build.VERSION.SDK_INT>=android.os.Build.VERSION_CODES.LOLLIPOP)cm.removeAllCookies(null)else cm.removeAllCookie();cm.flush();webView.clearCache(true);webView.clearHistory();webView.clearFormData();webView.reload()}
  fun emit(t:String,d:Any){onMessage(mapOf("payload" to mapOf("type" to t,"data" to d)))}
  fun notify(t:String,a:String,s:Long,th:String){service?.notify(t,a,s,th)}
  fun notifyProgress(p:Boolean,pos:Long){service?.notifyProgress(p,pos);currentActivity?.runOnUiThread{webView.keepScreenOn=p;customView?.keepScreenOn=p;if(p&&wakeLock!=null&&!wakeLock!!.isHeld)try{wakeLock!!.acquire(10*60*1000L)}catch(_:Exception){}else if(!p&&wakeLock!=null&&wakeLock!!.isHeld)try{wakeLock!!.release()}catch(_:Exception){}}}
  fun onOrientationChanged(o:Int){val a=currentActivity;if(a?.requestedOrientation==ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE&&(o in 70..110||o in 250..290))a.requestedOrientation=ActivityInfo.SCREEN_ORIENTATION_USER}
  fun getPageUrl():String=pageUrl
  fun exit(){service?.exit();if(wakeLock!=null&&wakeLock!!.isHeld)wakeLock!!.release()}
}
